my:
  first: hello1

banner:
      location: https://shreedhan.paymonk.com/offers/banner.txt

datasource:
  master:
    username: deepak
    password: D33p@k#ab
    url: jdbc:mysql://10.0.3.45:3306/dba
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    username: deepak
    password: D33p@k#ab
    url: jdbc:mysql://10.0.3.45:3306/dba
    driver-class-name: com.mysql.cj.jdbc.Driver
